version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb+srv://aadip2501_db_user:MMCOExTED2620@cluster0.b7nq6nx.mongodb.net/tedxmmcoe?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=change_this_secret_in_production
      - NODE_ENV=production
      - EMAIL_USER=${EMAIL_USER}
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
    volumes:
      - ./uploads:/app/uploads
    restart: always

volumes:
  mongo-data:
